web:
  image: techknowlogick/testlink:web
  volumes_from:
    - testlink
  links:
    - php:php
  ports:
    - "80:80"
  environment:
    - DATABASE_HOST=db
    - DATABASE_PASS=testlink

php:
  image: techknowlogick/testlink:php
  volumes_from:
    - testlink
    - testlink_data
  links:
    - db:db

db:
  image: postgres:9.4
  restart: always
  environment:
    - POSTGRES_DB=testlink
    - POSTGRES_PASSWORD=testlink
    - POSTGRES_USER=testlink
  volumes:
    - data:/var/lib/postgresql/data

testlink:
  build: .
  dockerfile: Dockerfile

testlink_data:
  image: techknowlogick/testlink:data
