web:
  image: techknowlogick/openresty:latest
  volumes_from:
    - testlink
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - php:php
  ports:
    - 80
  environment:
    - DATABASE_HOST=db
    - DATABASE_PASS=testlink

php:
  image: techknowlogick/testlink:php
  volumes_from:
    - testlink
    - testlink_data
  links:
    - db:db

db:
  image: mariadb:10
  environment:
   - MYSQL_DATABASE=testlink
   - MYSQL_ROOT_PASSWORD=testlink

testlink:
  image: techknowlogick/testlink:latest

testlink_data:
  image: techknowlogick/testlink:data